- apt: deb={{ct_submit_deb}}

- file: dest=/usr/lib/acme/hooks state=directory

- template: src=templates/ct-hook.sh dest=/usr/lib/acme/hooks/ct-hook.sh

- file: dest=/usr/lib/acme/hooks/ct-hook.sh mode=0755
